name: Update Watchtower Feed

'on':
  workflow_dispatch:

jobs:
  test_jw_api:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v6

      - name: Run JW.org test
        run: python update_feed.py
